---
title: "Simulation Example"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    theme: yeti
    highlight: tango
    toc: true
    toc_float: 
      collapsed: true
      smooth_scroll: true
    fig_width: 6
    fig_height: 4
---

# Load Package
```{r}
library(MMVBVS)
library(ggplot2)
```
# Create Data
```{r}
beta = c(seq(0.1, 0.5, length=5), rep(0,5))
n = 500; T = length(beta); nu = T+5
Sigma = matrix(0.8, T, T); diag(Sigma) = 1
X = as.numeric(scale(rnorm(n)))
error = MASS::mvrnorm(n, rep(0,T), Sigma)
gamma = c(rep(1,5), rep(0,5))
Y = X %*% t(beta) + error; Y = scale(Y)
for (i in 1:10){
  Y[sample(1:400, 200), i] = NA
}
```

# Run Algorithm

```{r}
Phi = matrix(0.5, T, T); diag(Phi) = 1
initial_chain = list(beta = rep(0,T), 
                      gamma = rep(0,T), 
                      Sigma = Phi, 
                      sigmabeta = 1)
result = mmvbvs(X = X,
                Y = Y,
                initial_chain = initial_chain,
                Phi = Phi,
                marcor = colMeans(X*Y, na.rm=TRUE),
                niter=100,
                verbose = FALSE)
```

# Analyze Result

## Inclusion of each tissue by iterations

```{r, fig.height = 5, fig.width = 4}
plot_gamma(result, title = "")
```

## Trajectory of $\beta$ by iterations
```{r, fig.width = 4, fig.height = 3.5}
plot_beta(result, title="")
```

## Posterior Distribution of the coefficients $\beta$
```{r}
beta_dist(result, title="")
```

## Heatmap of Posterior Mean of $\Sigma$
```{r}
plot_sigma(result, title="")
```
