# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator
# token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colmeanNA <- function(Y) {
    .Call("_MMVBVS_colmeanNA", PACKAGE = "MMVBVS", Y)
}

sample_index <- function(size, prob = as.numeric(c())) {
    .Call("_MMVBVS_sample_index", PACKAGE = "MMVBVS", size, prob)
}

mvrnormArma <- function(n, mu, Sigma) {
    .Call("_MMVBVS_mvrnormArma", PACKAGE = "MMVBVS", n, mu, Sigma)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE) {
    .Call("_MMVBVS_dmvnrm_arma", PACKAGE = "MMVBVS", x, mean, sigma, logd)
}

em_with_zero_mean_c <- function(y, maxit) {
    .Call("_MMVBVS_em_with_zero_mean_c", PACKAGE = "MMVBVS", y, maxit)
}

rinvwish_c <- function(n, v, S) {
    .Call("_MMVBVS_rinvwish_c", PACKAGE = "MMVBVS", n, v, S)
}

get_target_c <- function(X, Y, sigmabeta, Sigma, gam, beta) {
    .Call("_MMVBVS_get_target_c", PACKAGE = "MMVBVS", X, Y, sigmabeta, Sigma, gam, 
        beta)
}

update_Sigma_c <- function(n, nu, X, beta, Phi, Y) {
    .Call("_MMVBVS_update_Sigma_c", PACKAGE = "MMVBVS", n, nu, X, beta, Phi, Y)
}

update_gamma_random_c <- function(X, Y, gam) {
    .Call("_MMVBVS_update_gamma_random_c", PACKAGE = "MMVBVS", X, Y, gam)
}

betagam_accept_random_c <- function(X, Y, sigmabeta1, inputSigma, Vbeta, gam1, beta1, 
    gam2, beta2, changeind, change) {
    .Call("_MMVBVS_betagam_accept_random_c", PACKAGE = "MMVBVS", X, Y, sigmabeta1, 
        inputSigma, Vbeta, gam1, beta1, gam2, beta2, changeind, change)
}

update_betagam_random_c <- function(X, Y, gam1, beta1, Sigma, sigmabeta, Vbeta, 
    bgiter, smallchange) {
    .Call("_MMVBVS_update_betagam_random_c", PACKAGE = "MMVBVS", X, Y, gam1, beta1, 
        Sigma, sigmabeta, Vbeta, bgiter, smallchange)
}

get_sigmabeta_from_h_c <- function(h, gam, Sigma, X, T) {
    .Call("_MMVBVS_get_sigmabeta_from_h_c", PACKAGE = "MMVBVS", h, gam, Sigma, X, 
        T)
}

get_h_from_sigmabeta_c <- function(X, sigmabeta, Sigma, gam, n, T) {
    .Call("_MMVBVS_get_h_from_sigmabeta_c", PACKAGE = "MMVBVS", X, sigmabeta, Sigma, 
        gam, n, T)
}

update_h_c <- function(initialh, hiter, gam, beta, Sig, X, T) {
    .Call("_MMVBVS_update_h_c", PACKAGE = "MMVBVS", initialh, hiter, gam, beta, 
        Sig, X, T)
}

mmvbvs <- function(X, Y, initial_chain, Phi, marcor, sigmabeta, niter = 1000L, bgiter = 500L, 
    hiter = 50L, burnin = 100000L, Vbeta = 1L, smallchange = 1e-04, verbose = TRUE) {
    .Call("_MMVBVS_mmvbvs", PACKAGE = "MMVBVS", X, Y, initial_chain, Phi, marcor, 
        sigmabeta, niter, bgiter, hiter, burnin, Vbeta, smallchange, verbose)
}

